### PR TITLE
directly reference internal data. Closes #70

### LINKED ISSUE #70: Error in strptime(xx, f, tz = tz) : invalid 'tz' value
## Expected Behavior

Fetching weather using `weather_dl()`.

## Current Behavior

```
> mont_bellevue <- weather_dl(station_ids = 5397,
+                             start = "2019-02-01",
+                             end = "2019-02-07",
+                             interval = "hour",
+                             verbose = TRUE)
Getting station: 5397
Formatting station data: 5397
Error in strptime(xx, f, tz = tz) : invalid 'tz' value
```

## Steps to Reproduce (for bugs)
I'm doing a lot computations before getting the error. I tried several things and could not create a reproducible example.

## Possible Solution
Imcompatibility with another package?

## Context
I'm trying to build a gitbook with several chapters. A chapter including weathercan can be run alone, but the whole book (i.e. compiling previous chapters beforehand) throws the error.

## Your Environment
```
- Session info --------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  French_France.1252          
 ctype    French_France.1252          
 tz       America/New_York            
 date     2019-03-15                  

- Packages ------------------------------------------------------------------------------------------------
 ! package        * version    date       lib source                                      
   agridat        * 1.16       2018-07-06 [1] CRAN (R 3.5.1)                              
   assertthat       0.2.0      2017-04-11 [1] CRAN (R 3.5.1)                              
   backports        1.1.3      2018-12-14 [1] CRAN (R 3.5.2)                              
   base64enc        0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                              
   bayesm         * 3.1-1      2018-12-21 [1] CRAN (R 3.5.2)                              
   bookdown         0.9        2018-12-21 [1] CRAN (R 3.5.2)                              
   boot             1.3-20     2017-08-06 [2] CRAN (R 3.5.3)                              
   broom            0.5.1      2018-12-05 [1] CRAN (R 3.5.2)                              
   callr            3.1.1      2018-12-21 [1] CRAN (R 3.5.2)                              
   cellranger       1.1.0      2016-07-27 [1] CRAN (R 3.5.1)                              
   cli              1.0.1      2018-09-25 [1] CRAN (R 3.5.1)                              
   cluster          2.0.7-1    2018-04-13 [2] CRAN (R 3.5.3)                              
   coda             0.19-2     2018-10-08 [1] CRAN (R 3.5.1)                              
   codetools        0.2-16     2018-12-24 [2] CRAN (R 3.5.3)                              
   colorspace       1.4-0      2019-01-13 [1] CRAN (R 3.5.2)                              
   compositions   * 1.40-2     2018-06-14 [1] CRAN (R 3.5.2)                              
   cranlogs         2.1.0      2015-12-07 [1] CRAN (R 3.5.2)                              
   crayon           1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                              
   curl             3.3        2019-01-10 [1] CRAN (R 3.5.2)                              
   data.table       1.12.0     2019-01-13 [1] CRAN (R 3.5.2)                              
   DEoptimR         1.0-8      2016-11-19 [1] CRAN (R 3.5.0)                              
   desc             1.2.0      2018-05-01 [1] CRAN (R 3.5.1)                              
   devtools         2.0.1      2018-10-26 [1] CRAN (R 3.5.1)                              
   digest           0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                              
   dplyr          * 0.8.0.1    2019-02-15 [1] CRAN (R 3.5.3)                              
   ellipsis         0.1.0      2019-02-19 [1] CRAN (R 3.5.3)                              
   energy         * 1.7-5      2018-08-11 [1] CRAN (R 3.5.1)                              
   evaluate         0.13       2019-02-12 [1] CRAN (R 3.5.2)                              
   fansi            0.4.0      2018-10-05 [1] CRAN (R 3.5.1)                              
   forcats        * 0.4.0      2019-02-17 [1] CRAN (R 3.5.3)                              
   formattable      0.2.0.1    2016-08-05 [1] CRAN (R 3.5.2)                              
   fs               1.2.6      2018-08-23 [1] CRAN (R 3.5.1)                              
   future           1.12.0     2019-03-08 [1] CRAN (R 3.5.3)                              
   generics         0.0.2      2018-11-29 [1] CRAN (R 3.5.1)                              
   ggplot2        * 3.1.0      2018-10-25 [1] CRAN (R 3.5.1)                              
   globals          0.12.4     2018-10-11 [1] CRAN (R 3.5.2)                              
   glue             1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                              
   greta          * 0.3.0      2018-10-30 [1] CRAN (R 3.5.3)                              
   gtable           0.2.0      2016-02-26 [1] CRAN (R 3.5.1)                              
   haven            2.1.0      2019-02-19 [1] CRAN (R 3.5.3)                              
   hms              0.4.2      2018-03-10 [1] CRAN (R 3.5.1)                              
   htmltools        0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                              
   htmlwidgets      1.3        2018-09-30 [1] CRAN (R 3.5.1)                              
   httr             1.4.0      2018-12-11 [1] CRAN (R 3.5.1)                              
   janitor          1.1.1      2018-07-31 [1] CRAN (R 3.5.2)                              
   jsonlite         1.6        2018-12-07 [1] CRAN (R 3.5.1)                              
   knitr            1.22       2019-03-08 [1] CRAN (R 3.5.3)                              
   labeling         0.3        2014-08-23 [1] CRAN (R 3.5.0)                              
   lattice        * 0.20-38    2018-11-04 [1] CRAN (R 3.5.1)                              
   lazyeval         0.2.1      2017-10-29 [1] CRAN (R 3.5.1)                              
   listenv          0.7.0      2018-01-21 [1] CRAN (R 3.5.3)                              
   lubridate      * 1.7.4      2018-04-11 [1] CRAN (R 3.5.1)                              
   magrittr         1.5        2014-11-22 [1] CRAN (R 3.5.1)                              
   MASS             7.3-51.1   2018-11-01 [1] CRAN (R 3.5.1)                              
 R Matrix           1.2-15     <NA>       [2] <NA>                                        
   memoise          1.1.0      2017-04-21 [1] CRAN (R 3.5.1)                              
   mgcv             1.8-27     2019-02-06 [1] CRAN (R 3.5.2)                              
   modelr           0.1.4      2019-02-18 [1] CRAN (R 3.5.3)                              
   munsell          0.5.0      2018-06-12 [1] CRAN (R 3.5.1)                              
   nlme           * 3.1-137    2018-04-07 [2] CRAN (R 3.5.3)                              
   packagemetrics * 0.0.1.9001 2019-03-15 [1] Github (ropenscilabs/packagemetrics@00846df)
   packrat          0.5.0      2018-11-14 [1] CRAN (R 3.5.1)                              
   permute        * 0.9-5      2019-03-12 [1] CRAN (R 3.5.3)                              
   pillar           1.3.1      2018-12-15 [1] CRAN (R 3.5.2)                              
   pkgbuild         1.0.2      2018-10-16 [1] CRAN (R 3.5.1)                              
   pkgconfig        2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                              
   pkgload          1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                              
   plotly         * 4.8.0      2018-07-20 [1] CRAN (R 3.5.1)                              
   pls            * 2.7-0      2018-08-21 [1] CRAN (R 3.5.1)                              
   plyr             1.8.4      2016-06-08 [1] CRAN (R 3.5.1)                              
   prettyunits      1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                              
   processx         3.3.0      2019-03-10 [1] CRAN (R 3.5.3)                              
   progress         1.2.0      2018-06-14 [1] CRAN (R 3.5.1)                              
   ps               1.3.0      2018-12-21 [1] CRAN (R 3.5.2)                              
   purrr          * 0.3.1      2019-03-03 [1] CRAN (R 3.5.3)                              
   R6               2.4.0      2019-02-14 [1] CRAN (R 3.5.1)                              
   Rcpp             1.0.0      2018-11-07 [1] CRAN (R 3.5.1)                              
   readr          * 1.3.1      2018-12-21 [1] CRAN (R 3.5.2)                              
   readxl           1.3.1      2019-03-13 [1] CRAN (R 3.5.3)                              
   remotes          2.0.2      2018-10-30 [1] CRAN (R 3.5.1)                              
   reshape2         1.4.3      2017-12-11 [1] CRAN (R 3.5.1)                              
   reticulate       1.11.1     2019-03-06 [1] CRAN (R 3.5.3)                              
   rlang            0.3.1      2019-01-08 [1] CRAN (R 3.5.2)                              
   rmarkdown        1.12       2019-03-14 [1] CRAN (R 3.5.2)                              
   robustbase     * 0.93-3     2018-09-21 [1] CRAN (R 3.5.1)                              
   rprojroot        1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                              
   rsconnect        0.8.13     2019-01-10 [1] CRAN (R 3.5.2)                              
   rstudioapi       0.9.0      2019-01-09 [1] CRAN (R 3.5.2)                              
   rvest            0.3.2      2016-06-17 [1] CRAN (R 3.5.1)                              
   scales           1.0.0      2018-08-09 [1] CRAN (R 3.5.1)                              
   selectr          0.4-1      2018-04-06 [1] CRAN (R 3.5.1)                              
   sessioninfo      1.1.1      2018-11-05 [1] CRAN (R 3.5.1)                              
   skimr            1.0.5      2019-02-25 [1] CRAN (R 3.5.3)                              
   sp               1.3-1      2018-06-05 [1] CRAN (R 3.5.1)                              
   stringi          1.4.3      2019-03-12 [1] CRAN (R 3.5.3)                              
   stringr        * 1.4.0      2019-02-10 [1] CRAN (R 3.5.2)                              
   tensorA        * 0.36.1     2018-07-29 [1] CRAN (R 3.5.1)                              
   tensorflow       1.10       2018-11-19 [1] CRAN (R 3.5.1)                              
   tfruns           1.4        2018-08-25 [1] CRAN (R 3.5.1)                              
   tibble         * 2.0.1      2019-01-12 [1] CRAN (R 3.5.2)                              
   tidyr          * 0.8.3      2019-03-01 [1] CRAN (R 3.5.3)                              
   tidyselect       0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                              
   tidyverse      * 1.2.1      2017-11-14 [1] CRAN (R 3.5.3)                              
   usethis          1.4.0      2018-08-14 [1] CRAN (R 3.5.1)                              
   utf8             1.1.4      2018-05-24 [1] CRAN (R 3.5.1)                              
   vegan          * 2.5-4      2019-02-04 [1] CRAN (R 3.5.2)                              
   viridisLite      0.3.0      2018-02-01 [1] CRAN (R 3.5.1)                              
   weathercan     * 0.2.8      2018-10-08 [1] CRAN (R 3.5.1)                              
   whisker          0.3-2      2013-04-28 [1] CRAN (R 3.5.1)                              
   withr            2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                              
   xfun             0.5        2019-02-20 [1] CRAN (R 3.5.3)                              
   xml2             1.2.0      2018-01-24 [1] CRAN (R 3.5.1)                              
   yaml             2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                              

[1] C:/Users/essi/Documents/R/win-library/3.5
[2] C:/Program Files/R/R-3.5.3/library

 R -- Package was removed from disk.
```

### PR DESCRIPTION
**Pull request by boshek**
## Description
Looks like the internal data wasn't explicitly being reference so any floating objects of the same name got passed into the function. I'm not totally clear on how but directly referencing the `stations` dataframe will avoid this. 

## Related Issue
Closes #70

### CODE REVIEW

File: R/weather.R [hunk 1]
```diff
@@ -246,7 +246,7 @@ weather_dl <- function(station_ids,
         if(verbose) message("Formatting station data: ", s)
         w <- weather_format(w = w,
                             preamble = preamble,
-                            stations = stations,
+                            stations = weathercan::stations,
```
Comment (steffilazerte) [inline R/weather.R]:
```suggestion
                            stn = stn,
```

Comment (steffilazerte) [reply R/weather.R]: The `weather_dl()` function uses `stn` to specify the stations data frame. So if we make this change here, and then below, in the `weather_format()` function change all references to `stations` to `stn`. This should fix the environment conflict while still allowing users to specify their own updated station data frame.

**Comment by boshek** [comment]
Right that makes and explains the vagrant `stations` object.
